
<!-- Begin  This code is written by vinod kotiya
var a = (Math.random() +" ") 
var rand1 = Math.floor(a.charAt(5) * a * 12345) % 40;
//document.write(rand1);
quotes = new Array
quotes[1] = "ANY SUFFICIENTLY ADVANCED TECHNOLOGY IS INDISTINGUISHIBLE FROM MAGIC."
quotes[2] = "ALL GREAT DISCOVERIES ARE MADE BY MISTAKES."
quotes[3] = "DO NOT BELIEVE IN MIRACLES,RELY ON THEM."
quotes[4] = "ALWAYS DRAW YOUR CURVES,THEN PLOT YOUR READINGS."
quotes[5] = "ALL INSTRUMENTS WHEN DROPPED WILL ROLL INTO THE LEAST ACCESSIBLE CORNER."
quotes[6] = "NOTHING IS AS EASY AS IT LOOKS."
quotes[7] = "EVERYTHING TAKES LONGER THAN YOU THINK."
quotes[8] = "IT IS IMPOSIBLE TO MAKING ANYTHING FOOLPROOF BECAUSE FOOLS ARE SO INGENIOUS."
quotes[9] = "IF EVERYTHING SEEMS TO BE GOING WELL,YOU HAVE OBVIOUSLY OVERLOOKED SOMETHING."
quotes[10] = "LEFT TO THEMSELVES,THINGS TEND TO GO FROM BAD TO WORSE."
quotes[11] = "IF IT IS NOT IN THE COMPUTER IT DOES NOT EXIST."
quotes[12] = "EVERY SOLUTION BREEDS NEW PROBLEMS."
quotes[13] = "YOU NEVER RUN OUT OF THINGS THAT CAN GO WRONG."
quotes[14] = "IF A PROGRAM IS USELESS,IT WILL HAVE TO BE DOCUMENTED."
quotes[15] = "ANY PROGRAM WILL EXPAND TO FILL AVAILABLE MEMORY."
quotes[16] = " MATTER WILL BE DAMAGED IN DIRECT PROPORTION TO ITS VALUE."
quotes[17] = "  EVERYTHING GOES WRONG ALL AT ONCE."
quotes[18] = "WHEN AN ERROR HAS BEEN DETECTED AND CORRECTED, IT WILL BE FOUND TO HAVE BEEN CORRECT IN THE FIRST PLACE."
quotes[19] = " IF AN EXPERIMENT WORKS, SOMETHING HAS GONE WRONG."
quotes[20] = "  IN ANY COLLECTION OF DATA, THE FIGURE MOST OBVIOUSLY CORRECT, BEYOND ALL NEED OF CHECKING, IS THE MISTAKE."
quotes[21] = "THE VALUE OF A PROGRAM IS PROPOTIONAL TO THE WEIGHT OF ITS OUTPUT."
quotes[22] = "ANY NON-TRIVIAL PROGRAM CONTAINS ATLEAST ONE BUG."
quotes[23] = "UNDETECTABLE ERRORS ARE INFINITE IN VARIETY,IN CONTRAST TO DETECTABLE ERRORS,WHICH BY DEFINATION ARE FINITE."
quotes[24] = "PAPER IS ALWAYS STRONGEST AT THE PERFORMANCE."
quotes[25] = "EXPERIMENT SHOULD BE REPRODUCIBLE,THEY SHOULD ALL FAIL IN THE SAME WAY."
quotes[26] = "DO NOT BELIEVE IN MIRACLES,RELY ON THEM."
quotes[27] = "MACHINE SHOULD WORK,PEOPLE SHOULD THINK."
quotes[28] = "WHEN ALL ELSE FAILS,READ THE INSTRUCTIONS."
quotes[29] = "ANY ATTEMPT TO PRINT vinsoft's webpage JAM THE PRINTER. "
quotes[30] = "NEW SYSTEM GENERATES NEW PROBLEMS."
quotes[31] = " IT IS A MISTAKE TO ALLOW ANY MECHANICAL OBJECT TO REALIZE THAT YOU ARE IN A HURRY."
quotes[32] = " AFTER THINGS HAVE GONE FROM BAD TO WORSE, THE CYCLE WILL REPEAT ITSELF."
quotes[33] = " LOGIC IS A SYSTEMATIC METHOD OF COMING TO THE WRONG CONCLUSION WITH CONFIDENCE."
quotes[34] = " IF ANYTHING CAN GO WRONG, IT WILL."
quotes[35] = " IN CRISES THAT FORCE PEOPLE TO CHOOSE AMONG ALTERNATIVE COURSES OF ACTION, MOST PEOPLE WILL  CHOOSE THE WORST ONE POSSIBLE."
quotes[36] = " THINGS WILL GET WORSE BEFORE THEY WILL GET BETTER. WHO SAID THINGS WOULD GET BETTER?"
quotes[37] = " EVERYONE HAS A SCHEME THAT WILL NOT WORK."
quotes[38] = " The Law OF TIME: When the TRAIN you are on is late, the TRAIN you want to transfer to is on time."
quotes[39] = " kotiya's Ovservation: The chance of the bread falling with the butter side down  is directly proportional to the value of the carpet."
quotes[40] = "ANY GIVEN PROGRAM WHEN RUNNING IS OBSOLETE(old fashioned)."
quotes[0] = "THE FASTER A COMPUTER IS ,THE FASTER IT WILL RICH TO A CRASHED STATE."


var quote = quotes[rand1]
document.write(quote);

// End -->

