//  **************************************************************************
//  *******************  Author : Vinod Kotiya *******************************
//  ************ B.E.3rd yr(Information Technology) **************************
//  ***************** Bhopal Engg College Bhopal *****************************
//  *******Address:- s-2 shrimaya apartment sector-b/363 sarvdharm ***********
//  **************** Colony ,Bhopal Fone: +91-9827394994 ********************
//  ************ web http://vinodkotiya.tripod.com  ********************
//  ************     http://vinsoftindia.tripod.com *******************
//  ************ mail vinodkotiya@yahoo.co.in       ********************
//  **************************************************************************

#include<stdio.h>
#include<conio.h>


int main(void)
{
 clrscr();

 char c = 'v';

 printf("%d%d",sizeof(c),sizeof('v'));

 getch();
 return 1;
}

































