//  **************************************************************************
//  *******************  Author : Vinod Kotiya *******************************
//  ************ B.E.3rd yr(Information Technology) **************************
//  ***************** Bhopal Engg College Bhopal *****************************
//  *******Address:- s-2 shrimaya apartment sector-b/363 sarvdharm ***********
//  **************** Colony ,Bhopal Fone: +91-9827394994 ********************
//  ************ web http://vinodkotiya.tripod.com  ********************
//  ************     http://vinsoftindia.tripod.com *******************
//  ************ mail vinodkotiya@yahoo.co.in       ********************
//  **************************************************************************

#include<stdio.h>
#include<conio.h>


int main(void)
{
 clrscr();
 int i=32,j=0x20,k,l,m;
 k = i|j;
 l = i & j;
 m = k^l;

 printf("%d%d%d%d%d",i,j,k,l,m);

 //getch();
 //return 1;
}

































