//  **************************************************************************
//  *******************  Author : Vinod Kotiya *******************************
//  ************ B.E.3rd yr(Information Technology) **************************
//  ***************** Bhopal Engg College Bhopal *****************************
//  *******Address:- s-2 shrimaya apartment sector-b/363 sarvdharm ***********
//  **************** Colony ,Bhopal Fone: +91-9827394994 ********************
//  ************ web http://vinodkotiya.tripod.com  ********************
//  ************     http://vinsoftindia.tripod.com *******************
//  ************ mail vinodkotiya@yahoo.co.in       ********************
//  **************************************************************************

#include<stdio.h>
#include<conio.h>

int main(void)
{
 clrscr();
 float x=0.7;
 if(x<0.7)
 printf("c");
 else
 printf("c++");

 getch();
 return 1;
}

































